services:
  postgres:
    build: .
    container_name: my_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_users
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
    driver: local
